// Re-export types from shared schema
export type {
  User,
  InsertUser,
  Account,
  InsertAccount,
  Transaction,
  InsertTransaction,
  Category,
  InsertCategory,
  Goal,
  InsertGoal,
  Allocation,
  InsertAllocation,
  TransferRecommendation,
  InsertTransferRecommendation,
  CryptoWallet,
  InsertCryptoWallet,
  BudgetPeriod,
  InsertBudgetPeriod,
  BudgetCategory,
  InsertBudgetCategory,
  BudgetAccount,
  InsertBudgetAccount,
  ImportBatch,
  InsertImportBatch,
  ImportHistory,
  InsertImportHistory,
  TransactionHash,
  InsertTransactionHash,
  TransferPreference,
  InsertTransferPreference,
} from '@shared/schema';